Ordinal Encodeing

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


In [3]:
df = pd.read_csv('customer.csv')

In [5]:
df.shape

(50, 5)

In [99]:
df.sample(5)

age  gender   review education purchased
29   83  Female  Average        UG       Yes
26   53  Female     Poor        PG        No
8    65  Female  Average        UG        No
39   76    Male     Poor        PG        No
3    72  Female     Good        PG        No

In [100]:
df = df.iloc[:,2:]

In [101]:
df.head(38)

review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes
15     Poor        UG        No
16     Poor        UG       Yes
17     Poor        UG       Yes
18     Good    School        No
19     Poor        PG       Yes
20  Average    School       Yes
21  Average        PG        No
22     Poor        PG       Yes
23     Good    School        No
24  Average        PG       Yes
25     Good    School        No
26     Poor        PG        No
27     Poor        PG        No
28     Poor    School        No
29  Average        UG       Yes
30  Average        UG        No
31     Poor    School       Yes
32  Average        UG       Yes
33     Good        PG       Yes
34  Average    School        No
35     Poor    School       Yes
36     Good        UG       Yes
37  Average        PG       Yes

In [102]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)
from sklearn.preprocessing import OrdinalEncoder

In [103]:
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [104]:
x_train.head()

review education
41     Good        PG
39     Poor        PG
29  Average        UG
35     Poor    School
15     Poor        UG

In [105]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [106]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [107]:
x_train = oe.transform(x_train)
x_test = oe.transform(x_test)

In [108]:
x_train

array([[2., 2.],
       [0., 2.],
       [1., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [2., 2.],
       [1., 1.],
       [0., 1.],
       [0., 2.],
       [2., 0.],
       [1., 0.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [2., 1.],
       [1., 1.],
       [2., 1.],
       [0., 1.],
       [2., 1.],
       [2., 1.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [1., 2.],
       [0., 2.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [1., 2.],
       [1., 1.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [1., 0.]])

In [109]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [110]:
from sklearn.preprocessing import LabelEncoder

In [111]:
le = LabelEncoder()

In [112]:
le.fit(y_train)

LabelEncoder()

In [113]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [114]:
y_train = le.transform(y_test)
y_test = le.transform(y_test)

In [115]:
y_train

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 1])

One-Hot Encodeing

In [116]:
import pandas as pd
import numpy as np

In [117]:
df = pd.read_csv('cars.csv')

In [118]:
df.head()

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [119]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [120]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:4,],df.iloc[:,-1],test_size=0.2,random_state=2)

In [121]:
x_train.head()

brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [122]:
from sklearn.preprocessing import OneHotEncoder

In [123]:
ohe = OneHotEncoder(drop='first',dtype=np.int32)

In [124]:
x_train_new = ohe.fit_transform(x_train[['owner','fuel']]).toarray()

In [125]:
x_test_new = ohe.fit_transform(x_test[['fuel','owner']]).toarray()

In [126]:
x_train_new

array([[0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 1, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0]], dtype=int32)

In [127]:
x_train_new

array([[0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 1, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0]], dtype=int32)

In [128]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new))

array([['Hyundai', 35000, 0, ..., 1, 0, 0],
       ['Jeep', 60000, 0, ..., 1, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 1],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 1],
       ['Maruti', 32500, 0, ..., 1, 0, 0],
       ['Isuzu', 121000, 0, ..., 1, 0, 0]], dtype=object)

In [129]:
counts = df['brand'].value_counts()

In [130]:
df['brand'].nunique()
threshold = 100

In [131]:
repl = counts[counts<=threshold].index

In [134]:
pd.get_dummies(df['brand'].replace(repl,'uncommon'),dtype=np.int32).sample(5)

BMW  Chevrolet  Ford  Honda  Hyundai  Mahindra  Maruti  Renault  Skoda  \
742     0          0     0      0        0         1       0        0      0   
6440    0          0     0      0        0         1       0        0      0   
4736    0          0     0      0        0         0       0        0      0   
1976    0          0     0      0        0         0       1        0      0   
4674    0          0     0      0        1         0       0        0      0   

      Tata  Toyota  Volkswagen  uncommon  
742      0       0           0         0  
6440     0       0           0         0  
4736     0       1           0         0  
1976     0       0           0         0  
4674     0       0           0         0